- name: Installation install software-properties-common
  apt: name=software-properties-common

- name: "Repo PHP 8.3"
  apt_repository: repo="ppa:ondrej/php"

- name: "Updating the repo"
  apt: update_cache=yes

- name: Installation PHP 8.3
  apt:
    name:
      - php8.3
      - php8.3-fpm
    state: present
  notify: Enable PHP-FPM service

- name: Install PHP 8.3 and required extensions
  apt:
    name:
      - php8.3-bcmath
      - php8.3-bz2
      - php8.3-dev
      - php8.3-curl
      - php8.3-dom
      - php8.3-gd
      - php8.3-cli
      - php8.3-igbinary
      - php8.3-imagick
      - php8.3-imap
      - php8.3-intl
      - php8.3-ldap
      - php8.3-mbstring
      - php8.3-memcache
      - php8.3-memcached
      - php8.3-msgpack
      - php8.3-mysqli
      - php8.3-mysqlnd
      - php8.3-odbc
      - php8.3-pdo-mysql
      - php8.3-pdo-odbc
      - php8.3-pdo-sqlite
      - php8.3-rdkafka
      - unixodbc
      - unixodbc-dev
      - php8.3-redis
      - php8.3-simplexml
      - php8.3-soap
      - php8.3-sqlite3
      - php8.3-ssh2
      - php8.3-xml
      - php8.3-xmlreader
      - php8.3-xmlwriter
      - php8.3-xsl
      - php8.3-zip
    state: present
  become: true

- name: copy config php-fpm
  template:
    src: php.ini.j2
    dest: /etc/php/8.3/fpm/php.ini
    mode: 0644
    owner: root

- name: copy config php-fpm
  template:
    src: www.conf.j2
    dest: /etc/php/8.3/fpm/pool.d/www.conf
    mode: 0755
    owner: root

- name: config opcache
  template:
    src: 10-opcache.ini.j2
    dest: /etc/php/8.3/fpm/conf.d/10-opcache.ini
    mode: 0755
    owner: root
  notify: Start PHP-FPM service
