- name: Check List User
  include_vars:
    file: ../../../global_vars/user.yaml

- name: Create New User on list
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    append: yes
  loop: "{{ users }}"

- name: Add SSH keys for users
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.sshkey }}"
  loop: "{{ users }}"

- name: Add sudo permissions for users
  become: true
  lineinfile:
    path: "/etc/sudoers.d/{{ item.username }}"
    create: yes
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  loop: "{{ users }}"
